name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # Add this line to grant write permissions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Create env file
        run: |
          echo "VITE_FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}" > .env.production

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
